### ISSUE TITLE
Port Proactive Disclosure functionality to Drupal 8 

### ISSUE THREAD

**Issue by sylus** [open-data/od#5]
## Technologies Involved

  - CKAN (2.5)
  - Solr (5.0+)
  - Drupal 8

Drupal is the integration point between these technologies as it will be used to
interact with and display data from the given Solr cores often with widely
different schemas. Thankfully this is easily solved in Drupal 8 thanks to the
well laid path made in previous releases.

## Drupal 8

  - search_api
  - search_api_solr
  - search_api_solr_external (formerly named sarnia)

### Search API

This module provides a framework for easily creating searches on any entity
known to Drupal, using any kind of search engine. For site administrators, it
is a great alternative to other search solutions, since it already incorporates
faceting support and the ability to use the Views module for displaying search
results, filters, etc.

### Search API for Solr

`Search API for Solr` provides Search API with the `Solr` backend which uses
`Apache Solr` server for indexing content. `Search API for Solr` directly
leverages `Solarium` which is the PHP Solr client library.

### Search API for Solr External Cores

`Solr External Cores` allows a Drupal site to interact with and display data
from Solr cores that often can contain arbitrary schemas. This is incredibly
useful as these large external datasets will remain indexed and stored in Solr.

`Solr External Cores` treats every individual record retrieved from Solr via
a RESTful query as a Drupal entity. Consequently we can now perform direct
listing, filtering, faceting and formatting of the records now in Drupal. Each
Solr property can be formatted within Views fields using field formatters.

### Technical Discussion

Given the following Solr cores:

* core_ati
* core_contracts(a)
* core_grants
* core_hospitality(a|q)
* core_reclassification
* core_travel(a|q)
* core_wrongdoing

Each core will be given:

* search_api_server
* search_api_index

#### search_api_server

Rough approximation for an export.

```yml
  langcode: en
  status: true
  dependencies:
    module:
      - sarnia
      - search_api_solr
  id: pd_core_name
  name: 'Proactive Disclosure: Core Name'
  description: 'Proactive Disclosure: Core Name.'
  backend: sarnia_solr_service
  backend_config:
    connector: standard
    connector_config:
      scheme: http
      host: solr
      port: '8983'
      path: /solr
      core: core_name
      timeout: '5'
      index_timeout: '10'
      optimize_timeout: '15'
      solr_version: ''
      http_method: AUTO
    retrieve_data: 1
    highlight_data: 0
    excerpt: 0
    skip_schema_check: 0
    sarnia_request_handler: ''
    sarnia_default_query: '*:*'
    site_hash: 1
    autocorrect_spell: true
    autocorrect_suggest_words: true
```

#### search_api_index

Rough approximation for an export.

```yml
  langcode: en
  status: true
  dependencies:
    config:
      - search_api.server.pd_core_name
    module:
      - search_api
  id: pd_core_name
  name: 'Proactive Disclosure: Core Name (index)'
  description: 'Proactive Disclosure: Core Name (index).'
  read_only: true
  field_settings:
    url:
      label: URI
      property_path: search_api_url
      type: string
    ###
    ### Edited list of fields retrieved from Solr core.
    ###
  processor_settings:
    add_url:
      plugin_id: add_url
      settings: {  }
    ###
    ### Edited list of processor settings related to fields above.
    ###
  options:
    cron_limit: 0
    index_directly: false
  datasource_settings: {  }
  tracker_settings:
    default:
      plugin_id: default
      settings: {  }
  server: pd_core_name
```
